# Site settings
title: Dolen - developer Front End
description: dolen - blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 'dolen'
user_description: Front-End Developer
email: dolen.sirupe@gmail.com
twitter_username: imcts
github_username:  imcts
gplus_username:  imcts
disqus_username: 'dolen'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: true

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
